ims/ims/addons/tenant/admin/urls.py
from django.urls import re_path
from ims.addons.tenant.admin import views

app_name='ims.addons.tenant.admin'
urlpatterns = [
    re_path(r'^$', views.tenant_home, name='home'),
    re_path(r'^organization/$', views.admin_organization_view, name='admin_organization_view'),
    re_path(r'^organization/create/$', views.admin_organization_create, name='admin_organization_create'),
    re_path(r'^organization/change/(?P<id>[\d]+)/$', views.admin_organization_change, name='admin_organization_change'),
    re_path(r'^organization/delete/(?P<id>[\d]+)/$', views.ajax_organization_delete, name='ajax_organization_delete'),
    re_path(r'^userorganization/$', views.admin_userorganization_view, name='admin_userorganization_view'),
    re_path(r'^userorganization/create/$', views.admin_userorganization_create, name='admin_userorganization_create'),
    re_path(r'^userorganization/delete/(?P<id>[\d]+)/$', views.ajax_userorganization_delete, name='ajax_userorganization_delete'),
]

ims/ims/addons/tenant/api/urls.py
from django.urls import re_path
from ims.addons.tenant.api import views

app_name = 'ims.addons.tenant.api'
urlpatterns = [
    re_path(r'^organization/$', views.OrganizationList.as_view(), name='organization_list'),
    re_path(r'^organization/(?P<id>[\.\d]+)/$', views.OrganizationDetail.as_view(), name='organization_detail'),
    re_path(r'^userorganization/$', views.UserOrganizationList.as_view(), name='UserOrganization_list'),
    re_path(r'^userorganization/(?P<id>[\.\d]+)/$', views.UserOrganizationDetail.as_view(), name='UserOrganization_detail'),
]

ims/ims/addons/tenant/urls.py
from django.urls import re_path
from ims.addons.tenant import views

app_name='ims.addons.tenant'
urlpatterns = [
    re_path(r'^/$', views.part_list, name='home'),
    re_path(r'^ajax/(?P<model>[\w]+)/$', views.ajax, name='ajax_call'),
]

ims/ims/addons/tenant/models.py
from datetime import datetime
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.dispatch import receiver
from django.urls import reverse
from itertools import chain
import logging

from inventory.models import Part, Storage, PartStorage, AlternateSKU, PartAlternateSKU, Assembly, Kit, KitPartStorage

logger = logging.getLogger(__name__)

class Organization(models.Model):
    name = models.CharField(max_length=256)
    description = models.CharField(max_length=256)
    enabled = models.BooleanField(default=True)
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, null=True)
    created = models.DateTimeField(auto_now_add=True,editable=False)
    lastmodified = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        logger.debug('Generating absolute URL for Organization id {}'.format(self.id))
        return reverse('ims.addons.tenant:organization_detail', args=[self.id])

    #def get_users(self):

    #def get_suborg(self):

class UserOrganization(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True,editable=False)
    lastmodified = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['organization','user']

    def __str__(self):
        return str('{}-{}'.format(self.organization, self.user))

class TenantPart(models.Model):
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    part = models.OneToOneField(Part, on_delete=models.CASCADE, related_name='tenant')

    class Meta:
        ordering = ['organization','part']

class TenantStorage(models.Model):
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    storage = models.OneToOneField(Storage, on_delete=models.CASCADE, related_name='tenant')
    
    class Meta:
        ordering = ['organization','storage']

class TenantPartStorage(models.Model):
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    partstorage = models.OneToOneField(PartStorage, on_delete=models.CASCADE, related_name='tenant')

    class Meta:
        ordering = ['organization','partstorage']

class TenantAlternateSKU(models.Model):
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    alternatesku = models.OneToOneField(AlternateSKU, on_delete=models.CASCADE, related_name='tenant')
    
    class Meta:
        ordering = ['organization','alternatesku']

class TenantPartAlternateSKU(models.Model):
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    partalternatesku = models.OneToOneField(PartAlternateSKU, on_delete=models.CASCADE, related_name='tenant')
    
    class Meta:
        ordering = ['organization','partalternatesku']

class TenantAssembly(models.Model):
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    assembly = models.OneToOneField(Assembly, on_delete=models.CASCADE, related_name='tenant')

    class Meta:
        ordering = ['organization','assembly']

class TenantKit(models.Model):
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    kit = models.OneToOneField(Kit, on_delete=models.CASCADE, related_name='tenant')
    
    class Meta:
        ordering = ['organization','kit']

class TenantKitPartStorage(models.Model):
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    kitpartstorage = models.OneToOneField(KitPartStorage, on_delete=models.CASCADE, related_name='tenant')
    
    class Meta:
        ordering = ['organization','kitpartstorage']

ims/ims/addons/tenant/api/forms.py
from django import forms
from ims.addons.tenant.models import Organization, UserOrganization

class OrganizationForm(forms.ModelForm):
    class Meta:
        model = Organization
        fields = ('name','description','parent','enabled')

class UserOrganizationForm(forms.ModelForm):
    class Meta:
        model = UserOrganization
        fields = ('user','organization')

ims/ims/addons/tenant/admin/views.py
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.conf import settings
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect
import logging

from ims.addons.tenant.admin.forms import TenantForm, TenantPOSTForm, TenantViewOnlyForm, OrganizationForm, UserOrganizationForm
from ims.addons.tenant.models import Organization, UserOrganization
from inventory.search import Search
from log.logger import getLogger
import ims.addons.tenant.helpers as helpers

logger = logging.getLogger(__name__)
logger2 = getLogger('inventory-admin')
logger3 = getLogger('tenant-admin')

@login_required()
def home(request):
    cname = 'home'
    logger.debug('Request made to {} view'.format(cname))
    logger2.debug(request.user, 'Request to view Admin Home')
    logger.debug('Rendering request for {} view'.format(cname))
    logger2.info(request.user, 'Accessed Admin Home')
    return render(request, 'tenant/admin/home.html')

@permission_required('inventory.view_part')
def admin_part_view(request):
    return admin_generic_view('admin_part_view', 'Part', request)

@permission_required('inventory.add_part')
def admin_part_create(request):
    return admin_generic_create('admin_part_create', 'Part', request)

@permission_required('inventory.change_part')
def admin_part_change(request, id):
    return admin_generic_change('admin_part_change', 'Part', request, id)

def ajax_part_delete(request, id):
    return ajax_generic_delete('ajax_part_delete', 'Part', request, id)

@permission_required('inventory.view_assembly')
def admin_assembly_view(request):
    return admin_generic_view('admin_assembly_view', 'Assembly', request)

@permission_required('inventory.add_assembly')
def admin_assembly_create(request):
    return admin_generic_create('admin_assembly_create', 'Assembly', request)

@permission_required('inventory.change_assembly')
def admin_assembly_change(request, id):
    return admin_generic_change('admin_assembly_change', 'Assembly', request, id)

def ajax_assembly_delete(request, id):
    return ajax_generic_delete('ajax_assembly_delete', 'Assembly', request, id)

@permission_required('inventory.view_storage')
def admin_storage_view(request):
    return admin_generic_view('admin_storage_view', 'Storage', request)

@permission_required('inventory.add_storage')
def admin_storage_create(request):
    return admin_generic_create('admin_storage_create', 'Storage', request)

@permission_required('inventory.change_storage')
def admin_storage_change(request, id):
    return admin_generic_change('admin_storage_change', 'Storage', request, id)

def ajax_storage_delete(request, id):
    return ajax_generic_delete('ajax_storage_delete', 'Storage', request, id)

@permission_required('inventory.view_alternatesku')
def admin_alternatesku_view(request):
    return admin_generic_view('admin_alternatesku_view', 'AlternateSKU', request)

@permission_required('inventory.add_alternatesku')
def admin_alternatesku_create(request):
    return admin_generic_create('admin_alternatesku_create', 'AlternateSKU', request)

def ajax_alternatesku_delete(request, id):
    return ajax_generic_delete('ajax_alternatesku_delete', 'AlternateSKU', request, id)

@permission_required('inventory.view_partstorage')
def admin_partstorage_view(request):
    return admin_generic_view('admin_partstorage_view', 'PartStorage', request)

@permission_required('inventory.add_partstorage')
def admin_partstorage_create(request):
    return admin_generic_create('admin_partstorage_create', 'PartStorage', request)

@permission_required('inventory.change_partstorage')
def admin_partstorage_change(request, id):
    return admin_generic_change('admin_partstorage_change', 'PartStorage', request, id)

def ajax_partstorage_delete(request, id):
    return ajax_generic_delete('ajax_partstorage_delete', 'PartStorage', request, id)

@permission_required('inventory.view_partalternatesku')
def admin_partalternatesku_view(request):
    return admin_generic_view('admin_partalternatesku_view', 'PartAlternateSKU', request)

@permission_required('inventory.add_partalternatesku')
def admin_partalternatesku_create(request):
    return admin_generic_create('admin_partalternatesku_create', 'PartAlternateSKU', request)

def ajax_partalternatesku_delete(request, id):
    return ajax_generic_delete('ajax_partalternatesku_delete', 'PartAlternateSKU', request, id)

@permission_required('inventory.view_kit')
def admin_kit_view(request):
    return admin_generic_view('admin_kit_view', 'Kit', request)

@permission_required('inventory.add_kit')
def admin_kit_create(request):
    return admin_generic_create('admin_kit_create', 'Kit', request)

@permission_required('inventory.change_kit')
def admin_kit_change(request, id):
    return admin_generic_change('admin_kit_change', 'Kit', request, id)

def ajax_kit_delete(request, id):
    return ajax_generic_delete('ajax_kit_delete', 'Kit', request, id)

@permission_required('inventory.view_kitpartstorage')
def admin_kitpartstorage_view(request):
    return admin_generic_view('admin_kitpartstorage_view', 'KitPartStorage', request)

@permission_required('inventory.add_kitpartstorage')
def admin_kitpartstorage_create(request):
    return admin_generic_create('admin_kitpartstorage_create', 'KitPartStorage', request)

@permission_required('inventory.change_kitpartstorage')
def admin_kitpartstorage_change(request, id):
    return admin_generic_change('admin_kitpartstorage_change', 'KitPartStorage', request, id)

def ajax_kitpartstorage_delete(request, id):
    return ajax_generic_delete('ajax_kitpartstorage_delete', 'KitPartStorage', request, id)

def tenant_home_check(user):
    return user.has_perm('tenant.view_organization')|user.has_perm('tenant.view_userorganization')

@user_passes_test(tenant_home_check)
def tenant_home(request):
    cname = 'tenant_home'
    logger.debug('Request made to {} view'.format(cname))
    logger3.debug(request.user, 'Request to view Tenant Admin Home')
    if request.user.is_staff:
        logger.debug('Rendering request for {} view'.format(cname))
        logger3.info(request.user, 'Accessed Tenant Admin Home')
        return render(request, 'tenant/admin/tenant_home.html')
    logger.debug('User not authorized to view Tenant Admin Home')
    logger3.warning(request.user, 'User not authorized to view Tenant Admin Home')
    return redirect('/inventory/')

@permission_required('tenant.view_organization')
def admin_organization_view(request):
    cname = 'admin_organization_view'
    model = 'Organization'
    logger.debug('Request made to {} view'.format(cname))
    logger3.debug(request.user, 'Request to view Admin {} List'.format(model))
    if request.user.is_staff:
        object_list = Organization.objects.all()
        paginator = Paginator(object_list, settings.ADMIN_PAGE_SIZE)
        page = request.GET.get('page')
        # Try to display the page or catch and process the errors
        try:
            object_list = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver the first page
            logger.debug('PageNotAnInteger, show page 1')
            object_list = paginator.page(1)
        except EmptyPage:
            # If page is out of range, deliver the last page
            logger.debug('EmptyPage, show page {}'.format(paginator.num_pages))
            object_list = paginator.page(paginator.num_pages)
        logger.debug('Rendering request for {} view'.format(cname))
        logger3.info(request.user, 'Accessed Admin {} List'.format(model))
        return render(request, 'tenant/admin/tenant_view.html', {'name': model, 'objs': object_list, 'allowupdate': True})
    logger.debug('User not authorized to view Admin {} List'.format(model))
    logger3.warning(request.user, 'User not authorized to view Admin {} List'.format(model))
    return redirect('/inventory/')

@permission_required('tenant.add_organization')
def admin_organization_create(request):
    cname = 'admin_organization_create'
    model = 'Organization'
    logger.debug('Request made to {} view'.format(cname))
    logger3.debug(request.user, 'Request to view Admin Create {} Page'.format(model))
    if request.user.is_staff:
        if request.method == 'POST':
            logger.debug('Serializing the request data')
            form = OrganizationForm(request.POST)
            if form.is_valid():
                logger.debug('{} is valid.'.format(form.__class__.__name__))
                logger.info('Creating new {} "{}"'.format(model, form.fields['name']))
                org = form.save()
                logger3.info(request.user, 'Created {} id {}'.format(model, org.id))
                return redirect('/tenant/admin/')
            logger.debug('Form is not valid. Rendering request for {} view'.format(cname))
            logger3.warning(request.user, 'Create {} Form not valid'.format(model))
            return render(request, 'tenant/admin/tenant_create.html', {'name': model, 'form': form, 'message': 'Form is not valid.'})
        form = OrganizationForm()
        logger.debug('Generated a new {} and checking for provided variables'.format(form.__class__.__name__))
        logger.debug('Rendering request for {} view'.format(cname))
        logger3.info(request.user, 'Accessed Admin Create {} page'.format(model))
        return render(request, 'tenant/admin/tenant_create.html', {'name': model, 'form': form})
    logger.debug('User not authorized to view Admin Create {} page'.format(model))
    logger3.warning(request.user, 'User not authorized to view Admin Create {} page'.format(model))
    return redirect('/inventory/')

@permission_required('tenant.change_organization')
def admin_organization_change(request, id):
    cname = 'admin_organization_change'
    model = 'Organization'

ims/templates/tenant/admin/create.html
{% extends "inventory/base.html" %}
{% load static %}
{% load get_setting %}
{% load custom_tags %}
{% block title %}New {{ name }}{% endblock %}
{% block content %}
<div class="w3-container w3-padding w3-light-gray" style="margin-top:20px;">
    <a href="/inventory/admin/" alt="Inventory Admin">Inventory Admin</a>
    »
    <a href="/inventory/admin/{{ name|lower }}/" alt="Inventory Admin {{ name }}">{{ name }}</a>
    » Add {{ name }}
</div>
<div class="w3-container" style="margin-top:65px;">
    <div class="w3-left w3-margin-top">
        <h4><b>New {{ name }}</b></h4>
    </div>
    <div class="w3-container">
        <div class="w3-col w3-padding w3-left">{{ message }}</div>
    </div>
    <div class="w3-container">
        <form class="w3-col l12 xl6 w3-card w3-padding w3-bar-block" action="." method="post">
            {% csrf_token %}
            {{ tenantform.non_field_errors }}
            {% for field in tenantform %}
            <div class="w3-bar-item">
                {{ field.errors }}
                {{ field | add_classes_and_auto_format:"w3-left ims-select-options ims-form-field" }}
            </div>
            {% endfor %}
            {{ form.non_field_errors }}
            {% for field in form %}
            <div class="w3-bar-item">
                {{ field.errors }}
                {{ field | add_classes_and_auto_format:"w3-left ims-select-options ims-form-field" }}
            </div>
            {% endfor %}
            <div class="w3-bar-item">
                <input type="submit" class="w3-button w3-dark-grey ims-form-field" value="Create">
            </div>
            <div class="w3-bar-item">
                <a href="/inventory/" class="w3-button w3-light-grey ims-form-field">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% if name == 'Assembly' or name == 'Storage' or name == 'PartStorage' or name == 'PartAlternateSKU' or name == 'KitPartStorage' %}
<script src="{% static "common/js/jquery.min.js" %}"></script>
<script>
    $("#id_organization").change(function() {
        var selectedId = $(this).val();
        {% if name == 'Assembly' or name == 'PartStorage' or name == 'PartAlternateSKU' %}
        $.ajax({
            url: '/tenant/ajax/part/',
            data: {
                'selected': selectedId
            },
            success: function(data){
                $("#id_part").html(data);
                {% if name == 'Assembly' %}
                $("#id_parent").html(data);
                {% endif %}
            }
        });
        {% endif %}
        {% if name == 'Storage' or name == 'PartStorage' %}
        $.ajax({
            url: '/tenant/ajax/storage/',
            data: {
                'selected': selectedId
            },
            success: function(data){
                {% if name == 'Storage' %}
                $("#id_parent").html(data);
                {% else %}
                $("#id_storage").html(data);
                {% endif %}
            }
        });
        {% elif name == 'PartAlternateSKU' %}
        $.ajax({
            url: '/tenant/ajax/alternatesku/',
            data: {
                'selected': selectedId
            },
            success: function(data){
                $("#id_alt_sku").html(data);
            }
        });
        {% elif name == 'KitPartStorage' %}
        $.ajax({
            url: '/tenant/ajax/kit/',
            data: {
                'selected': selectedId
            },
            success: function(data){
                $("#id_kit").html(data);
            }
        });
        $.ajax({
            url: '/tenant/ajax/partstorage/',
            data: {
                'selected': selectedId
            },
            success: function(data){
                $("#id_partstorage").html(data);
            }
        });
        {% endif %}
    });
</script>
{% endif %}
{% endblock %}

ims/templates/tenant/admin/home.html
{% extends "inventory/base.html" %}
{% load get_setting %}
{% load custom_tags %}
{% block title %}Inventory Admin{% endblock %}
{% block content %}
<div class="w3-container" style="margin-top:65px;">
    <div class="w3-left w3-margin-top">
        <h4><b>Inventory Admin</b></h4>
    </div>
    <div class="w3-container">
        <div class="w3-col l12 xl6 w3-card w3-padding w3-bar-block">
            <div class="w3-bar-item">
                {% if perms.inventory.view_part %}<a class="w3-button ims-form-field" href="/inventory/admin/part/">Part</a>{% endif %}
                {% if perms.inventory.view_assembly %}<a class="w3-button ims-form-field" href="/inventory/admin/assembly/">Assembly</a>{% endif %}
                {% if perms.inventory.view_storage %}<a class="w3-button ims-form-field" href="/inventory/admin/storage/">Storage</a>{% endif %}
                {% if perms.inventory.view_alternatesku %}<a class="w3-button ims-form-field" href="/inventory/admin/alternatesku/">AlternateSKU</a>{% endif %}
                {% if perms.inventory.view_partstorage %}<a class="w3-button ims-form-field" href="/inventory/admin/partstorage/">PartStorage</a>{% endif %}
                {% if perms.inventory.view_partalternatesku %}<a class="w3-button ims-form-field" href="/inventory/admin/partalternatesku/">PartAlternateSKU</a>{% endif %}
		        {% if perms.inventory.view_kit %}<a class="w3-button ims-form-field" href="/inventory/admin/kit/">Kit</a>{% endif %}
		        {% if perms.inventory.view_kitpartstorage %}<a class="w3-button ims-form-field" href="/inventory/admin/kitpartstorage/">KitPartStorage</a>{% endif %}
            </div>
	</div>
    </div>
</div>
{% endblock %}

ims/templates/tenant/admin/tenant_create.html
{% extends "inventory/base.html" %}
{% load static %}
{% load get_setting %}
{% load custom_tags %}
{% block title %}New {{ name }}{% endblock %}
{% block content %}
<div class="w3-container w3-padding w3-light-gray" style="margin-top:20px;">
    <a href="/tenant/admin/" alt="Tenant Admin">Tenant Admin</a>
    »
    <a href="/tenant/admin/{{ name|lower }}/" alt="Tenant Admin {{ name }}">{{ name }}</a>
    » Add {{ name }}
</div>
<div class="w3-container" style="margin-top:65px;">
    <div class="w3-left w3-margin-top">
        <h4><b>New {{ name }}</b></h4>
    </div>
    <div class="w3-container">
        <div class="w3-col w3-padding w3-left">{{ message }}</div>
    </div>
    <div class="w3-container">
        <form class="w3-col l12 xl6 w3-card w3-padding w3-bar-block" action="." method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form %}
            {% if field.field.widget.input_type == 'checkbox' %}
            <div class="w3-bar-item ims-chkb-wrap">
                {{ field.errors }}
                {{ field | add_classes:"ims-tgl ims-tgl-skewed" }}
		<label class="w3-left ims-form-field ims-tgl-btn" data-tg-off="Disabled" data-tg-on="Enabled" for="{{ field.id_for_label }}" />
            </div>
            {% else %}
            <div class="w3-bar-item">
                {{ field.errors }}
                {{ field | add_classes_and_auto_format:"w3-left ims-select-options ims-form-field" }}
            </div>
            {% endif %}
            {% endfor %}
            <div class="w3-bar-item">
                <input type="submit" class="w3-button w3-dark-grey ims-form-field" value="Create">
            </div>
            <div class="w3-bar-item">
                <a href="/tenant/admin/" class="w3-button w3-light-grey ims-form-field">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

ims/templates/tenant/admin/tenant_home.html
{% extends "inventory/base.html" %}
{% load get_setting %}
{% load custom_tags %}
{% block title %}Tenant Admin{% endblock %}
{% block content %}
<div class="w3-container" style="margin-top:65px;">
    <div class="w3-left w3-margin-top">
        <h4><b>Tenant Admin</b></h4>
    </div>
    <div class="w3-container">
        <div class="w3-col l12 xl6 w3-card w3-padding w3-bar-block">
            <div class="w3-bar-item">
                {% if perms.tenant.view_organization %}<a class="w3-button ims-form-field" href="/tenant/admin/organization/">Organization</a>{% endif %}
                {% if perms.tenant.view_userorganization %}<a class="w3-button ims-form-field" href="/tenant/admin/userorganization/">UserOrganization</a>{% endif %}
            </div>
	</div>
    </div>
</div>
{% endblock %}

ims/templates/tenant/admin/tenant_update.html
{% extends "inventory/base.html" %}
{% load get_setting %}
{% load custom_tags %}
{% block title %}Update {{ name }}{% endblock %}
{% block content %}
<div class="w3-container w3-padding w3-light-gray" style="margin-top:20px;">
    <a href="/tenant/admin/" alt="Tenant Admin">Tenant Admin</a>
    »
    <a href="/tenant/admin/{{ objtype|lower }}/" alt="Tenant Admin {{ objtype }}">{{ objtype }}</a>
    » {{ name }}
</div>
<div class="w3-container" style="margin-top:65px;">
    <div class="w3-left w3-margin-top">
        <h4><b>Update {{ name }}</b></h4>
    </div>
    <div class="w3-container">
        <div class="w3-col w3-padding w3-left">{{ message }}</div>
    </div>
    <div class="w3-container">
        <form class="w3-col l12 xl6 w3-card w3-padding w3-bar-block" action="." method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form %}
            {% if field.field.widget.input_type == 'checkbox' %}
            <div class="w3-bar-item ims-chkb-wrap">
                {{ field.errors }}
                {{ field | add_classes:"ims-tgl ims-tgl-skewed" }}
                <label class="w3-left ims-form-field ims-tgl-btn" data-tg-off="Disabled" data-tg-on="Enabled" for="{{ field.id_for_label }}" />
            </div>
            {% else %}
            <div class="w3-bar-item">
                {{ field.errors }}
                {{ field | add_classes_and_auto_format:"w3-left ims-select-options ims-form-field" }}
            </div>
            {% endif %}
            {% endfor %}
            <div class="w3-bar-item">
                <input type="submit" class="w3-button w3-dark-grey ims-form-field" value="Update">
            </div>
            <div class="w3-bar-item">
                <a href="/tenant/admin/" class="w3-button w3-light-grey ims-form-field">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

ims/templates/tenant/admin/update.html
{% extends "inventory/base.html" %}
{% load get_setting %}
{% load custom_tags %}
{% block title %}Update {{ name }}{% endblock %}
{% block content %}
<div class="w3-container w3-padding w3-light-gray" style="margin-top:20px;">
    <a href="/inventory/admin/" alt="Inventory Admin">Inventory Admin</a>
    »
    <a href="/inventory/admin/{{ objtype|lower }}/" alt="Inventory Admin {{ objtype }}">{{ objtype }}</a>
    » {{ name }}
</div>
<div class="w3-container" style="margin-top:65px;">
    <div class="w3-left w3-margin-top">
        <h4><b>Update {{ name }}</b></h4>
    </div>
    <div class="w3-container">
        <div class="w3-col w3-padding w3-left">{{ message }}</div>
    </div>
    <div class="w3-container">
        <form class="w3-col l12 xl6 w3-card w3-padding w3-bar-block" action="." method="post">
            {% csrf_token %}
            {{ tenantform.non_field_errors }}
            {% for field in tenantform %}
            <div class="w3-bar-item">
                {{ field.errors }}
                {{ field | add_classes_and_auto_format:"w3-left ims-select-options ims-form-field" }}
            </div>
            {% endfor %}
            {{ form.non_field_errors }}
            {% for field in form %}
            <div class="w3-bar-item">
                {{ field.errors }}
                {{ field | add_classes_and_auto_format:"w3-left ims-select-options ims-form-field" }}
            </div>
            {% endfor %}
            <div class="w3-bar-item">
                <input type="submit" class="w3-button w3-dark-grey ims-form-field" value="Update">
            </div>
            <div class="w3-bar-item">
                <a href="/inventory/" class="w3-button w3-light-grey ims-form-field">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}